### ISSUE TITLE
Dá pra colocar um reactzinho

### ISSUE THREAD

**Issue by daniloaleixo** [daniloaleixo/bovespaStockRatings#12]
Com o react consigo mudar bastante coisa, por exemplo fazer o filtro que estava querendo (#4)

**Comment by andrecgro** [comment]
Como ficou isso ?
O script ainda é rodado manualmente ? Dá pra colocar algo para rodar sempre que acessar o app.

**Comment by daniloaleixo** [comment]
Ainda não resolvi, estou pensando mudar pra usar angular na verdade que achei mais fácil o data table deles. 
E sobre rodar o script pra pegar as infos? Então ele roda em cima de um cron que pega uma vez por dia. Não acho que seria bom pegar as infos sempre que alguém acessar, porque o cron é uma transação bem custosa, provavelmente seria inviável pro servidor. Mas qual indicador vc queria pegar em tempo real?

**Comment by andrecgro** [comment]
Na verdade minha ideia era basicamente para garantir que esteja sempre atualizado. Você tinha dito que rodava na mão dai pensei que poderia não ser tão atualizado. Com o cron diário, está tranquilo mas com o React pode melhorar mesmo.

**Comment by daniloaleixo** [comment]
Eh então, eu percebi que estava bem ruim de filtrar e etc. Mas tinha até deixado de lado esse projeto. Daora que vc comentou que vou voltar a mexer

**Comment by andrecgro** [comment]
Bora fazer junto !
podemos criar um Discord/Slack ou algo assim e facilitar de comunicar por lá

**Comment by daniloaleixo** [comment]
Boaaaa,

Te mandei um invite do LinkedIn, ai a gente pode trocar contato ;)
